env=Environment(VAR="value")

env.Append(LINKFLAGS = [
    '-lm',
    ])

env.VariantDir('.', '../src', duplicate=0)

env.Append(CPPPATH = [
    '.',
    '#../inc',
    '#../font'
    ])

prg = [
    env.Program(
        target = 'test_log2',
        source = [
            'test_log2.c',
        ]
    ),
    env.Program(
        target = 'test_exposure',
        source = [
            'test_exposure.c',
            '../src/exponometer.c',
        ]
    ),
    env.Program(
        target = 'test_terminal',
        source = [
            'test_terminal.c',
            '../src/terminal.c',
            '../font/font_test.c',
        ]
    )]
