#ifndef _FONT_H_ 
#define _FONT_H_ 


#define BIG_FONT_WIDTH 16 
#define BIG_FONT_HEIGHT 16 

typedef enum {
	BIG_FONT_LATIN_CAPITAL_LETTER_A,
	BIG_FONT_LATIN_CAPITAL_LETTER_C,
	BIG_FONT_LATIN_CAPITAL_LETTER_L,
	BIG_FONT_LATIN_CAPITAL_LETTER_E,
	BIG_FONT_LATIN_CAPITAL_LETTER_X,
	BIG_FONT_LATIN_CAPITAL_LETTER_P,
	BIG_FONT_LATIN_CAPITAL_LETTER_T,
	BIG_FONT_LATIN_CAPITAL_LETTER_I,
	BIG_FONT_LATIN_CAPITAL_LETTER_M,
	BIG_FONT_LATIN_CAPITAL_LETTER_U,
	BIG_FONT_SPACE,
	BIG_FONT_MAX,
} big_chars;
extern const unsigned char *big_font_char_table[];

#define SMALL_FONT_WIDTH 8 
#define SMALL_FONT_HEIGHT 8 

typedef enum {
	SMALL_FONT_DIGIT_ZERO,
	SMALL_FONT_DIGIT_ONE,
	SMALL_FONT_DIGIT_TWO,
	SMALL_FONT_DIGIT_THREE,
	SMALL_FONT_DIGIT_FOUR,
	SMALL_FONT_DIGIT_FIVE,
	SMALL_FONT_DIGIT_SIX,
	SMALL_FONT_DIGIT_SEVEN,
	SMALL_FONT_DIGIT_EIGHT,
	SMALL_FONT_DIGIT_NINE,
	SMALL_FONT_LATIN_CAPITAL_LETTER_A,
	SMALL_FONT_LATIN_CAPITAL_LETTER_B,
	SMALL_FONT_LATIN_CAPITAL_LETTER_C,
	SMALL_FONT_LATIN_CAPITAL_LETTER_D,
	SMALL_FONT_LATIN_CAPITAL_LETTER_E,
	SMALL_FONT_LATIN_CAPITAL_LETTER_F,
	SMALL_FONT_LATIN_CAPITAL_LETTER_G,
	SMALL_FONT_LATIN_CAPITAL_LETTER_H,
	SMALL_FONT_LATIN_CAPITAL_LETTER_I,
	SMALL_FONT_LATIN_CAPITAL_LETTER_J,
	SMALL_FONT_LATIN_CAPITAL_LETTER_K,
	SMALL_FONT_LATIN_CAPITAL_LETTER_L,
	SMALL_FONT_LATIN_CAPITAL_LETTER_M,
	SMALL_FONT_LATIN_CAPITAL_LETTER_N,
	SMALL_FONT_LATIN_CAPITAL_LETTER_O,
	SMALL_FONT_LATIN_CAPITAL_LETTER_P,
	SMALL_FONT_LATIN_CAPITAL_LETTER_Q,
	SMALL_FONT_LATIN_CAPITAL_LETTER_R,
	SMALL_FONT_LATIN_CAPITAL_LETTER_S,
	SMALL_FONT_LATIN_CAPITAL_LETTER_T,
	SMALL_FONT_LATIN_CAPITAL_LETTER_U,
	SMALL_FONT_LATIN_CAPITAL_LETTER_V,
	SMALL_FONT_LATIN_CAPITAL_LETTER_W,
	SMALL_FONT_LATIN_CAPITAL_LETTER_X,
	SMALL_FONT_LATIN_CAPITAL_LETTER_Y,
	SMALL_FONT_LATIN_CAPITAL_LETTER_Z,
	SMALL_FONT_HYPHEN_MINUS,
	SMALL_FONT_PLUS_SIGN,
	SMALL_FONT_LOW_LINE,
	SMALL_FONT_SPACE,
	SMALL_FONT_MAX,
} small_chars;
extern const unsigned char *small_font_char_table[];
typedef enum {
	BIG_FONT,
	SMALL_FONT,
} fonts;
#endif //_FONT_H_ 
