#include "font.h" 

const unsigned char *big_font_char_table[] = {
	"0", //big_font_DIGIT_ZERO,
	"1", //big_font_DIGIT_ONE,
	"2", //big_font_DIGIT_TWO,
	"3", //big_font_DIGIT_THREE,
	"4", //big_font_DIGIT_FOUR,
	"5", //big_font_DIGIT_FIVE,
	"6", //big_font_DIGIT_SIX,
	"7", //big_font_DIGIT_SEVEN,
	"8", //big_font_DIGIT_EIGHT,
	"9", //big_font_DIGIT_NINE,
	"l", //big_font_LATIN_SMALL_LETTER_L,
	"u", //big_font_LATIN_SMALL_LETTER_U,
	"x", //big_font_LATIN_SMALL_LETTER_X,
	"e", //big_font_LATIN_SMALL_LETTER_E,
	"v", //big_font_LATIN_SMALL_LETTER_V,
	"m", //big_font_LATIN_SMALL_LETTER_M,
	"s", //big_font_LATIN_SMALL_LETTER_S,
	"i", //big_font_LATIN_SMALL_LETTER_I,
	"o", //big_font_LATIN_SMALL_LETTER_O,
	"f", //big_font_LATIN_SMALL_LETTER_F,
	"+", //big_font_PLUS_SIGN,
	"/", //big_font_SOLIDUS,
	"-", //big_font_HYPHEN_MINUS,
	".", //big_font_FULL_STOP,
	" ", //big_font_SPACE,
};
const unsigned char *small_font_char_table[] = {
	"0", //small_font_DIGIT_ZERO,
	"1", //small_font_DIGIT_ONE,
	"2", //small_font_DIGIT_TWO,
	"3", //small_font_DIGIT_THREE,
	"4", //small_font_DIGIT_FOUR,
	"5", //small_font_DIGIT_FIVE,
	"6", //small_font_DIGIT_SIX,
	"7", //small_font_DIGIT_SEVEN,
	"8", //small_font_DIGIT_EIGHT,
	"9", //small_font_DIGIT_NINE,
	"i", //small_font_LATIN_SMALL_LETTER_I,
	"s", //small_font_LATIN_SMALL_LETTER_S,
	"o", //small_font_LATIN_SMALL_LETTER_O,
	"e", //small_font_LATIN_SMALL_LETTER_E,
	"v", //small_font_LATIN_SMALL_LETTER_V,
	"p", //small_font_LATIN_SMALL_LETTER_P,
	"f", //small_font_LATIN_SMALL_LETTER_F,
	"m", //small_font_LATIN_SMALL_LETTER_M,
	"+", //small_font_PLUS_SIGN,
	"/", //small_font_SOLIDUS,
	"-", //small_font_HYPHEN_MINUS,
	".", //small_font_FULL_STOP,
	" ", //small_font_SPACE,
};
const unsigned char *special_font_char_table[] = {
	" ", //special_font_BAT_EMPTY,
	" ", //special_font_BAT_HALF,
	" ", //special_font_BAT_FULL,
	" ", //special_font_BAT_CHRG,
};
