#ifndef _FONT_H_ 
#define _FONT_H_ 


#define BIG_FONT_WIDTH 16 
#define BIG_FONT_HEIGHT 16 

typedef enum {
	BIG_FONT_DIGIT_ZERO,
	BIG_FONT_DIGIT_ONE,
	BIG_FONT_DIGIT_TWO,
	BIG_FONT_DIGIT_THREE,
	BIG_FONT_DIGIT_FOUR,
	BIG_FONT_DIGIT_FIVE,
	BIG_FONT_DIGIT_SIX,
	BIG_FONT_DIGIT_SEVEN,
	BIG_FONT_DIGIT_EIGHT,
	BIG_FONT_DIGIT_NINE,
	BIG_FONT_LATIN_SMALL_LETTER_L,
	BIG_FONT_LATIN_SMALL_LETTER_U,
	BIG_FONT_LATIN_SMALL_LETTER_X,
	BIG_FONT_LATIN_SMALL_LETTER_E,
	BIG_FONT_LATIN_SMALL_LETTER_V,
	BIG_FONT_LATIN_SMALL_LETTER_M,
	BIG_FONT_LATIN_SMALL_LETTER_S,
	BIG_FONT_LATIN_SMALL_LETTER_I,
	BIG_FONT_LATIN_SMALL_LETTER_O,
	BIG_FONT_LATIN_SMALL_LETTER_F,
	BIG_FONT_SOLIDUS,
	BIG_FONT_HYPHEN_MINUS,
	BIG_FONT_FULL_STOP,
	BIG_FONT_SPACE,
	BIG_FONT_MAX,
} big_chars;
extern const unsigned char *big_font_char_table[];

#define SMALL_FONT_WIDTH 8 
#define SMALL_FONT_HEIGHT 8 

typedef enum {
	SMALL_FONT_DIGIT_ZERO,
	SMALL_FONT_DIGIT_ONE,
	SMALL_FONT_DIGIT_TWO,
	SMALL_FONT_DIGIT_THREE,
	SMALL_FONT_DIGIT_FOUR,
	SMALL_FONT_DIGIT_FIVE,
	SMALL_FONT_DIGIT_SIX,
	SMALL_FONT_DIGIT_SEVEN,
	SMALL_FONT_DIGIT_EIGHT,
	SMALL_FONT_DIGIT_NINE,
	SMALL_FONT_LATIN_SMALL_LETTER_I,
	SMALL_FONT_LATIN_SMALL_LETTER_S,
	SMALL_FONT_LATIN_SMALL_LETTER_O,
	SMALL_FONT_LATIN_SMALL_LETTER_E,
	SMALL_FONT_LATIN_SMALL_LETTER_X,
	SMALL_FONT_LATIN_SMALL_LETTER_P,
	SMALL_FONT_LATIN_SMALL_LETTER_F,
	SMALL_FONT_LATIN_SMALL_LETTER_M,
	SMALL_FONT_SOLIDUS,
	SMALL_FONT_HYPHEN_MINUS,
	SMALL_FONT_FULL_STOP,
	SMALL_FONT_SPACE,
	SMALL_FONT_MAX,
} small_chars;
extern const unsigned char *small_font_char_table[];

#define SPECIAL_FONT_WIDTH 16 
#define SPECIAL_FONT_HEIGHT 16 

typedef enum {
	SPECIAL_FONT_BAT_EMPTY,
	SPECIAL_FONT_BAT_HALF,
	SPECIAL_FONT_BAT_FULL,
	SPECIAL_FONT_BAT_CHRG,
	SPECIAL_FONT_MAX,
} special_chars;
extern const unsigned char *special_font_char_table[];
typedef enum {
	BIG_FONT,
	SMALL_FONT,
	SPECIAL_FONT,
} fonts;
#endif //_FONT_H_ 
