#!python

import os
env = Environment(ENV = os.environ)
 
env['CC'] = 'sdcc'
env['CXX'] = 'sdcc'
env['LINK'] = 'sdcc'
env['OBJSUFFIX'] = '.rel'
env['PROGSUFFIX'] = '.ihx'

stm_device='STM8S003'

# include locations
env.Append(CPPPATH = [
    '#inc', 
    '#inc/stm8s/inc',
    ])

# compiler flags
env.Append(CCFLAGS = [
    '-mstm8',
    '-lstm8',
#    '--opt-code-size',
    '--std-c99',
    ])


env.Append(LINKFLAGS = [
    '-mstm8',
    '-lstm8',
    '--out-fmt-ihx',
    ]) 

# defines
env.Append(CPPDEFINES = [
    stm_device,
])


env.VariantDir('build/stm8/', 'src/stm8s/src', duplicate=0)
env.VariantDir('build/src/', 'src', duplicate=0)


#print(env.Dump())
# build everything
prg = env.Program(
    target = 'main',
    source = [
        'build/src/blinky.c',
        'build/stm8/stm8s_gpio.c',
    ]
)

